// @generated
// This file is @generated by prost-build.
/// This is an instance of an item
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryItem {
    /// It may be the ID from the database or the EntityPosition.ItemInstance.instance_id
    #[prost(string, tag="1")]
    pub item_instance_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub item_definition_id: u64,
    /// Amount is only used when the item is stackable
    #[prost(uint64, tag="3")]
    pub amount: u64,
    #[prost(bool, tag="4")]
    pub is_equipped: bool,
    #[prost(message, repeated, tag="5")]
    pub attributes: ::prost::alloc::vec::Vec<InventoryItemAttribute>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryItemAttribute {
    #[prost(enumeration="ItemAttributeDefinition", tag="1")]
    pub attr_definition: i32,
    #[prost(float, tag="2")]
    pub attr_value: f32,
}
/// / Here are all the attributes that items may contain.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ItemAttributeDefinition {
    IncreaseVitality = 0,
    IncreaseIntelligence = 1,
    IncreaseStrength = 2,
    IncreaseAgility = 3,
    /// Skill damage should take into account the dps of a weapon
    IncreaseWeaponDamage = 4,
    /// Skill damage should take into account the dps of a weapon
    IncreaseWeaponDamagePercentage = 5,
    /// Attack/Skill (including healing)
    IncreaseCriticalChancePercentage = 6,
    IncreaseCriticalDamagePercentage = 7,
    IncreaseMovementSpeedPercentage = 8,
    /// Chance for better drops on loot table
    IncreaseLuckPercentage = 9,
}
impl ItemAttributeDefinition {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::IncreaseVitality => "IncreaseVitality",
            Self::IncreaseIntelligence => "IncreaseIntelligence",
            Self::IncreaseStrength => "IncreaseStrength",
            Self::IncreaseAgility => "IncreaseAgility",
            Self::IncreaseWeaponDamage => "IncreaseWeaponDamage",
            Self::IncreaseWeaponDamagePercentage => "IncreaseWeaponDamagePercentage",
            Self::IncreaseCriticalChancePercentage => "IncreaseCriticalChancePercentage",
            Self::IncreaseCriticalDamagePercentage => "IncreaseCriticalDamagePercentage",
            Self::IncreaseMovementSpeedPercentage => "IncreaseMovementSpeedPercentage",
            Self::IncreaseLuckPercentage => "IncreaseLuckPercentage",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IncreaseVitality" => Some(Self::IncreaseVitality),
            "IncreaseIntelligence" => Some(Self::IncreaseIntelligence),
            "IncreaseStrength" => Some(Self::IncreaseStrength),
            "IncreaseAgility" => Some(Self::IncreaseAgility),
            "IncreaseWeaponDamage" => Some(Self::IncreaseWeaponDamage),
            "IncreaseWeaponDamagePercentage" => Some(Self::IncreaseWeaponDamagePercentage),
            "IncreaseCriticalChancePercentage" => Some(Self::IncreaseCriticalChancePercentage),
            "IncreaseCriticalDamagePercentage" => Some(Self::IncreaseCriticalDamagePercentage),
            "IncreaseMovementSpeedPercentage" => Some(Self::IncreaseMovementSpeedPercentage),
            "IncreaseLuckPercentage" => Some(Self::IncreaseLuckPercentage),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionResolveRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionResolveResponse {
    /// updated inventory
    #[prost(message, repeated, tag="1")]
    pub inventory: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRequest {
    #[prost(uint64, tag="1")]
    pub transaction_id: u64,
    /// using player uuid uses player inventory, using character uuid uses character inventory
    #[prost(string, tag="2")]
    pub inventory_source_uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionResponse {
    /// If the transaction takes longer than 0 seconds we get the transaction instance ids
    #[prost(message, repeated, tag="1")]
    pub transaction_instance_id: ::prost::alloc::vec::Vec<protobuf_itemdefinition::TransactionInstance>,
    /// updated inventory
    #[prost(message, repeated, tag="2")]
    pub inventory: ::prost::alloc::vec::Vec<InventoryItem>,
    /// what you got instantly
    #[prost(message, repeated, tag="3")]
    pub rewarded: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartQuestRequest {
    #[prost(string, tag="1")]
    pub character_uuid: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub quest_definition_id: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StartQuestResponse {
}
/// ---------- NETWORK ----------
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerInventoryRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInventoryResponse {
    #[prost(message, repeated, tag="1")]
    pub inventory: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantSellItemRequest {
    #[prost(string, tag="1")]
    pub character_uuid: ::prost::alloc::string::String,
    /// The merchant to buy things from
    #[prost(uint64, tag="2")]
    pub merchant_definition_id: u64,
    #[prost(message, optional, tag="3")]
    pub item: ::core::option::Option<InventoryItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantSellItemResponse {
    #[prost(message, repeated, tag="1")]
    pub inventory: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantBuyItemRequest {
    #[prost(string, tag="1")]
    pub character_uuid: ::prost::alloc::string::String,
    /// The merchant to buy things from
    #[prost(uint64, tag="2")]
    pub merchant_definition_id: u64,
    /// What you want to buy from the list of things available from the merchant
    #[prost(uint32, tag="3")]
    pub item_index: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantBuyItemResponse {
    #[prost(message, repeated, tag="1")]
    pub inventory: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusInstance {
    #[prost(uint64, tag="1")]
    pub definition_id: u64,
    #[prost(float, tag="4")]
    pub remaining_lifetime: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterInstance {
    #[prost(string, tag="1")]
    pub player_owner_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub character_uuid: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub character_definition_id: u64,
    #[prost(uint32, tag="4")]
    pub current_max_hp: u32,
    #[prost(int32, tag="5")]
    pub current_hp: i32,
    #[prost(message, repeated, tag="6")]
    pub visible_inventory: ::prost::alloc::vec::Vec<InventoryItem>,
    #[prost(string, tag="7")]
    pub character_name: ::prost::alloc::string::String,
    /// The private data, should only be present for your own player, but we can send it all for now
    #[prost(message, optional, tag="8")]
    pub private_instance: ::core::option::Option<CharacterPrivateInstance>,
    /// Buffs and debuffs
    #[prost(message, repeated, tag="9")]
    pub statuses: ::prost::alloc::vec::Vec<StatusInstance>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterPrivateInstance {
    #[prost(message, repeated, tag="2")]
    pub full_inventory: ::prost::alloc::vec::Vec<InventoryItem>,
    #[prost(uint32, tag="3")]
    pub agi_spent: u32,
    #[prost(uint32, tag="4")]
    pub int_spent: u32,
    #[prost(uint32, tag="5")]
    pub str_spent: u32,
    #[prost(uint32, tag="6")]
    pub vit_spent: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CharacterStat {
    Agi = 0,
    Int = 1,
    Str = 2,
    Vit = 3,
}
impl CharacterStat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Agi => "AGI",
            Self::Int => "INT",
            Self::Str => "STR",
            Self::Vit => "VIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGI" => Some(Self::Agi),
            "INT" => Some(Self::Int),
            "STR" => Some(Self::Str),
            "VIT" => Some(Self::Vit),
            _ => None,
        }
    }
}
/// Maybe we can have elemental damage later
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DamageType {
    Damage = 0,
    Heal = 1,
}
impl DamageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Damage => "Damage",
            Self::Heal => "Heal",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Damage" => Some(Self::Damage),
            "Heal" => Some(Self::Heal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Position {
    #[prost(float, tag="1")]
    pub x: f32,
    #[prost(float, tag="2")]
    pub y: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SpawnPoint {
    #[prost(uint64, tag="1")]
    pub enemy_definition_id: u64,
    #[prost(message, optional, tag="2")]
    pub position: ::core::option::Option<Position>,
    #[prost(uint64, tag="3")]
    pub spawn_rate_ms: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Teleporter {
    #[prost(uint64, tag="1")]
    pub connected_map_id: u64,
    #[prost(message, optional, tag="2")]
    pub position: ::core::option::Option<Position>,
    /// Using the door executes a transaction which could be just a required item.
    #[prost(uint64, tag="3")]
    pub transaction_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeshData {
    /// Mesh name/ID
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// Flattened \[x,y,z,x,y,z,...\]
    #[prost(float, repeated, tag="2")]
    pub vertices: ::prost::alloc::vec::Vec<f32>,
    /// Flattened \[x,y,z,...\]
    #[prost(float, repeated, tag="3")]
    pub normals: ::prost::alloc::vec::Vec<f32>,
    /// Flattened \[u,v,u,v,...\]
    #[prost(float, repeated, tag="4")]
    pub uvs: ::prost::alloc::vec::Vec<f32>,
    /// Triangles \[i1,i2,i3,...\]
    #[prost(int32, repeated, tag="5")]
    pub indices: ::prost::alloc::vec::Vec<i32>,
    /// (Optional) flattened RGBA per vertex
    #[prost(float, repeated, tag="6")]
    pub colors: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MobInstance {
    #[prost(uint64, tag="1")]
    pub definition_id: u64,
    #[prost(string, tag="2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub current_hp: u64,
    #[prost(uint64, tag="4")]
    pub max_hp: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillInstance {
    #[prost(uint64, tag="1")]
    pub definition_id: u64,
    #[prost(string, tag="2")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub owner_uuid: ::prost::alloc::string::String,
    #[prost(float, tag="4")]
    pub remaining_lifetime: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemInstance {
    #[prost(uint64, tag="1")]
    pub definition_id: u64,
    #[prost(string, tag="2")]
    pub instance_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub owner_uuid: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub value: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityPosition {
    #[prost(uint64, tag="1")]
    pub creation_timestamp: u64,
    #[prost(message, optional, tag="2")]
    pub position: ::core::option::Option<Position>,
    #[prost(oneof="entity_position::Entity", tags="3, 4, 5, 6, 7")]
    pub entity: ::core::option::Option<entity_position::Entity>,
}
/// Nested message and enum types in `EntityPosition`.
pub mod entity_position {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Entity {
        #[prost(message, tag="3")]
        Player(super::CharacterInstance),
        #[prost(message, tag="4")]
        Mob(super::MobInstance),
        #[prost(message, tag="5")]
        Skill(super::SkillInstance),
        #[prost(message, tag="6")]
        PickableItem(super::ItemInstance),
        #[prost(message, tag="7")]
        PickableInventoryItem(super::InventoryItem),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DamageInstance {
    #[prost(string, tag="1")]
    pub instance_id: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub creation_timestamp: u64,
    #[prost(message, optional, tag="3")]
    pub position: ::core::option::Option<Position>,
    #[prost(string, tag="4")]
    pub damage_owner_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub damage_target_uuid: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub damage_amount: u64,
    #[prost(bool, tag="7")]
    pub is_critical_hit: bool,
    #[prost(enumeration="DamageType", tag="8")]
    pub damage_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapState {
    #[prost(uint64, tag="1")]
    pub map_definition_id: u64,
    #[prost(message, repeated, tag="2")]
    pub entities: ::prost::alloc::vec::Vec<EntityPosition>,
    #[prost(message, repeated, tag="3")]
    pub damage_entities: ::prost::alloc::vec::Vec<DamageInstance>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapUpdateResponse {
    #[prost(message, optional, tag="1")]
    pub map_state: ::core::option::Option<MapState>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapJoinRequest {
    #[prost(uint64, tag="1")]
    pub map_uuid: u64,
    #[prost(string, tag="2")]
    pub character_uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapJoinResponse {
    #[prost(uint64, tag="1")]
    pub map_uuid: u64,
    #[prost(string, tag="2")]
    pub character_uuid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapActionRequest {
    #[prost(string, tag="1")]
    pub character_uuid: ::prost::alloc::string::String,
    #[prost(oneof="map_action_request::MapAction", tags="2, 3, 4, 5, 6")]
    pub map_action: ::core::option::Option<map_action_request::MapAction>,
}
/// Nested message and enum types in `MapActionRequest`.
pub mod map_action_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum MapAction {
        #[prost(message, tag="2")]
        MoveTo(super::MoveTo),
        #[prost(message, tag="3")]
        UsableSkill(super::UseSkill),
        #[prost(message, tag="4")]
        PickUpItem(super::PickUpItem),
        #[prost(message, tag="5")]
        UseTeleport(super::UseTeleport),
        #[prost(message, tag="6")]
        UseAbilityPoint(super::UseAbilityPoint),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MapActionResponse {
}
// Map Actions

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveTo {
    #[prost(message, repeated, tag="1")]
    pub target_positions: ::prost::alloc::vec::Vec<Position>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UseSkill {
    #[prost(uint64, tag="1")]
    pub skill_definition_id: u64,
    #[prost(message, optional, tag="2")]
    pub target_pos: ::core::option::Option<Position>,
    #[prost(message, optional, tag="3")]
    pub target_direction: ::core::option::Option<Position>,
    /// When the skill directly affects X entities
    #[prost(string, repeated, tag="4")]
    pub targets_uuid: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UseAbilityPoint {
    #[prost(enumeration="CharacterStat", tag="1")]
    pub stat: i32,
    #[prost(uint32, tag="2")]
    pub amount: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PickUpItem {
    #[prost(string, repeated, tag="1")]
    pub item_instance_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UseTeleport {
    #[prost(uint32, tag="1")]
    pub teleport_index: u32,
}
/// Allows dropping items. Only items which are not equipped and not invisible can be dropped
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DropItem {
    #[prost(message, repeated, tag="1")]
    pub item: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GameErrorCode {
    OkGame = 0,
    // ONES ABOVE ARE CORE ERRORS

    InvalidCharacter = 14,
    NotEnoughCharacterSlots = 15,
    InvalidCharacterStat = 16,
    PlayerIsNotInAnyMap = 17,
    QuestIsNotAvailable = 19,
    ItemSlotOccupied = 20,
    ItemIsNotEquipped = 22,
    SkillNotOwned = 23,
    InvalidMapId = 24,
    /// Actions that require an alive player, like loot, or move
    CharacterIsDeadAndCantPerformThatAction = 25,
    /// Actions that require a dead player, like revive
    CharacterIsNotDeadAndCantPerformThatAction = 26,
    UserCantSellItem = 27,
    MerchantInvalid = 28,
}
impl GameErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OkGame => "OK_GAME",
            Self::InvalidCharacter => "INVALID_CHARACTER",
            Self::NotEnoughCharacterSlots => "NOT_ENOUGH_CHARACTER_SLOTS",
            Self::InvalidCharacterStat => "INVALID_CHARACTER_STAT",
            Self::PlayerIsNotInAnyMap => "PLAYER_IS_NOT_IN_ANY_MAP",
            Self::QuestIsNotAvailable => "QUEST_IS_NOT_AVAILABLE",
            Self::ItemSlotOccupied => "ITEM_SLOT_OCCUPIED",
            Self::ItemIsNotEquipped => "ITEM_IS_NOT_EQUIPPED",
            Self::SkillNotOwned => "SKILL_NOT_OWNED",
            Self::InvalidMapId => "INVALID_MAP_ID",
            Self::CharacterIsDeadAndCantPerformThatAction => "CHARACTER_IS_DEAD_AND_CANT_PERFORM_THAT_ACTION",
            Self::CharacterIsNotDeadAndCantPerformThatAction => "CHARACTER_IS_NOT_DEAD_AND_CANT_PERFORM_THAT_ACTION",
            Self::UserCantSellItem => "USER_CANT_SELL_ITEM",
            Self::MerchantInvalid => "MERCHANT_INVALID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OK_GAME" => Some(Self::OkGame),
            "INVALID_CHARACTER" => Some(Self::InvalidCharacter),
            "NOT_ENOUGH_CHARACTER_SLOTS" => Some(Self::NotEnoughCharacterSlots),
            "INVALID_CHARACTER_STAT" => Some(Self::InvalidCharacterStat),
            "PLAYER_IS_NOT_IN_ANY_MAP" => Some(Self::PlayerIsNotInAnyMap),
            "QUEST_IS_NOT_AVAILABLE" => Some(Self::QuestIsNotAvailable),
            "ITEM_SLOT_OCCUPIED" => Some(Self::ItemSlotOccupied),
            "ITEM_IS_NOT_EQUIPPED" => Some(Self::ItemIsNotEquipped),
            "SKILL_NOT_OWNED" => Some(Self::SkillNotOwned),
            "INVALID_MAP_ID" => Some(Self::InvalidMapId),
            "CHARACTER_IS_DEAD_AND_CANT_PERFORM_THAT_ACTION" => Some(Self::CharacterIsDeadAndCantPerformThatAction),
            "CHARACTER_IS_NOT_DEAD_AND_CANT_PERFORM_THAT_ACTION" => Some(Self::CharacterIsNotDeadAndCantPerformThatAction),
            "USER_CANT_SELL_ITEM" => Some(Self::UserCantSellItem),
            "MERCHANT_INVALID" => Some(Self::MerchantInvalid),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimQuestRequest {
    #[prost(string, tag="1")]
    pub character_uuid: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub quest_definition_id: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClaimQuestResponse {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheatAddInventoryItemRequest {
    #[prost(string, tag="1")]
    pub player_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub character_uuid: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub item_def: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheatAddInventoryItemResponse {
    #[prost(string, tag="1")]
    pub player_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub character_uuid: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub inventory: ::prost::alloc::vec::Vec<InventoryItem>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CharactersQueryRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharactersQueryResponse {
    #[prost(message, repeated, tag="1")]
    pub owned_characters: ::prost::alloc::vec::Vec<CharacterInstance>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterReviveRequest {
    #[prost(string, tag="1")]
    pub character_uuid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CharacterReviveResponse {
    #[prost(uint64, tag="1")]
    pub map_definition_to_teleport: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterEquipRequest {
    #[prost(string, tag="1")]
    pub character_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub item_instance_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub should_equip: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CharacterEquipResponse {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterCreateRequest {
    #[prost(uint64, tag="1")]
    pub character_definition_id: u64,
    #[prost(string, tag="2")]
    pub character_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterCreateResponse {
    #[prost(message, optional, tag="1")]
    pub character: ::core::option::Option<CharacterInstance>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestInstance {
    #[prost(uint64, tag="1")]
    pub definition_id: u64,
    #[prost(enumeration="QuestStatus", tag="2")]
    pub status: i32,
    #[prost(message, optional, tag="3")]
    pub progress: ::core::option::Option<QuestProgress>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestProgress {
    #[prost(uint64, repeated, tag="1")]
    pub mob_definition_id: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint32, repeated, tag="2")]
    pub kill_amount: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QuestStatus {
    Unavailable = 0,
    Available = 1,
    InProgress = 2,
    Claimed = 3,
}
impl QuestStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unavailable => "Unavailable",
            Self::Available => "Available",
            Self::InProgress => "InProgress",
            Self::Claimed => "Claimed",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unavailable" => Some(Self::Unavailable),
            "Available" => Some(Self::Available),
            "InProgress" => Some(Self::InProgress),
            "Claimed" => Some(Self::Claimed),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LootTable {
    /// Min drops from the loot table
    #[prost(uint32, tag="1")]
    pub drop_count_min: u32,
    /// Max drops from the loot table
    #[prost(uint32, tag="2")]
    pub drop_count_max: u32,
    #[prost(message, repeated, tag="3")]
    pub droppable_items: ::prost::alloc::vec::Vec<WeightedDroppableItem>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WeightedDroppableItem {
    #[prost(message, optional, tag="1")]
    pub id_ref: ::core::option::Option<protobuf_itemdefinition::ItemDefinitionRef>,
    #[prost(uint32, tag="2")]
    pub min_value: u32,
    #[prost(uint32, tag="3")]
    pub max_value: u32,
    #[prost(uint32, tag="4")]
    pub weight: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EquipmentSlot {
    Helmet = 0,
    HandMain = 1,
    HandSecondary = 2,
    Armor = 3,
    Pants = 4,
    Gloves = 5,
    Boots = 6,
    Wings = 7,
    Familiar = 8,
    /// Invisible slots
    Amulet = 9,
    Ring = 10,
}
impl EquipmentSlot {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Helmet => "Helmet",
            Self::HandMain => "HandMain",
            Self::HandSecondary => "HandSecondary",
            Self::Armor => "Armor",
            Self::Pants => "Pants",
            Self::Gloves => "Gloves",
            Self::Boots => "Boots",
            Self::Wings => "Wings",
            Self::Familiar => "Familiar",
            Self::Amulet => "Amulet",
            Self::Ring => "Ring",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Helmet" => Some(Self::Helmet),
            "HandMain" => Some(Self::HandMain),
            "HandSecondary" => Some(Self::HandSecondary),
            "Armor" => Some(Self::Armor),
            "Pants" => Some(Self::Pants),
            "Gloves" => Some(Self::Gloves),
            "Boots" => Some(Self::Boots),
            "Wings" => Some(Self::Wings),
            "Familiar" => Some(Self::Familiar),
            "Amulet" => Some(Self::Amulet),
            "Ring" => Some(Self::Ring),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BtNode {
    #[prost(message, optional, tag="1")]
    pub any_node: ::core::option::Option<::prost_types::Any>,
}
/// / COMPOSITES
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BtNodeSequence {
    #[prost(message, repeated, tag="1")]
    pub children: ::prost::alloc::vec::Vec<BtNode>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BtNodeSelector {
    #[prost(message, repeated, tag="1")]
    pub children: ::prost::alloc::vec::Vec<BtNode>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BtNodeRepeat {
    #[prost(message, optional, tag="1")]
    pub child: ::core::option::Option<BtNode>,
    #[prost(enumeration="BtRepeatMode", tag="2")]
    pub repeat: i32,
    /// Only used when repeat mode is x_times
    #[prost(int32, tag="3")]
    pub count_times: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BtNodeWait {
    #[prost(float, tag="1")]
    pub duration_milliseconds: f32,
}
/// LEAFS ACTIONS
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BtNodeCalculateRandomPosition {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BtNodeMoveToRandomLocation {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BtNodeSpawnSkillOnTarget {
    #[prost(message, optional, tag="1")]
    pub skill_definition: ::core::option::Option<protobuf_itemdefinition::ItemDefinitionRef>,
    #[prost(uint64, tag="2")]
    pub override_damage: u64,
}
// LEAFS CONDITIONS

#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BtNodeIsCharacterInRange {
    #[prost(float, tag="1")]
    pub range: f32,
}
// DECORATORS

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BtRepeatMode {
    Once = 0,
    Forever = 1,
    XTimes = 2,
}
impl BtRepeatMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Once => "Once",
            Self::Forever => "Forever",
            Self::XTimes => "x_times",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Once" => Some(Self::Once),
            "Forever" => Some(Self::Forever),
            "x_times" => Some(Self::XTimes),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SkillComponent {
    /// Spawn size of radius 
    #[prost(float, tag="1")]
    pub radius_start: f32,
    /// Radius size at the end of the lifetime
    #[prost(float, tag="2")]
    pub radius_end: f32,
    /// How far away can the skill be spawned from the player
    #[prost(uint32, tag="3")]
    pub max_distance: u32,
    /// total duration of the skill
    #[prost(uint32, tag="4")]
    pub lifetime_millis: u32,
    /// how often it does the damage after the initial delay
    #[prost(uint32, tag="5")]
    pub trigger_interval_millis: u32,
    /// delays the first damage
    #[prost(uint32, tag="6")]
    pub start_delay_millis: u32,
    /// the skill can't be used again until this time has passed after usage
    #[prost(uint32, tag="7")]
    pub cooldown_millis: u32,
    /// How fast the skill moves away from the player
    #[prost(float, tag="8")]
    pub movement_speed: f32,
    #[prost(enumeration="SkillPositionCalculationMode", tag="9")]
    pub skill_position_calculation_mode: i32,
    #[prost(enumeration="SkillTickIntervalMode", tag="10")]
    pub skill_interval_mode: i32,
    #[prost(enumeration="SkillTargetMode", tag="11")]
    pub skill_taget_mode: i32,
    /// When the skill has a range and can affect multiple enemies, who should it affect
    #[prost(enumeration="SkillAoETargetType", tag="12")]
    pub aoe_target_type: i32,
    #[prost(message, optional, tag="13")]
    pub on_hit: ::core::option::Option<protobuf_itemdefinition::ItemDefinitionRef>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DamageOnHitComponent {
    #[prost(float, tag="1")]
    pub base_damage: f32,
    /// Adds a percentage of stats to the base damage 1 = 100% stat applied
    #[prost(float, tag="2")]
    pub strength_modifier: f32,
    #[prost(float, tag="3")]
    pub agility_modifier: f32,
    #[prost(float, tag="4")]
    pub intelligence_modifier: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealOnHitComponent {
    #[prost(float, tag="1")]
    pub base_heal: f32,
    /// Adds a percentage of stats to the base damage 1 = 100% stat applied
    #[prost(float, tag="2")]
    pub strength_modifier: f32,
    #[prost(float, tag="3")]
    pub agility_modifier: f32,
    #[prost(float, tag="4")]
    pub intelligence_modifier: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusOnHitComponent {
    /// total duration of the effect
    #[prost(uint64, tag="1")]
    pub lifetime_millis: u64,
    /// how often it triggers, 0 triggers once
    #[prost(uint32, tag="2")]
    pub interval_millis: u32,
    /// What kind of effect
    #[prost(enumeration="StatusType", tag="3")]
    pub effect_type: i32,
    /// Only if Status type is StatModifier
    #[prost(message, repeated, tag="4")]
    pub modifications: ::prost::alloc::vec::Vec<StatModification>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatModification {
    #[prost(enumeration="StatType", tag="1")]
    pub stat_type: i32,
    /// Modifies adds or removes a static amount, E.G. MaxHP +50
    #[prost(int64, tag="2")]
    pub plain: i64,
    /// Modifies adds or removes a percentage amount, E.G. MaxHP +10%
    #[prost(float, tag="3")]
    pub percentage: f32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SkillPositionCalculationMode {
    /// The skill position will be calculated on the client based on the mouse position, constrained by max_distance
    MousePos = 0,
    /// The skill position will be calculated using the position of the character, look at mouse position, given a max_distance
    LookAt = 1,
    /// The skill affects a specific target
    SelectedTarget = 2,
    /// Whoever casted the skill goes into its current position
    CasterPosition = 3,
}
impl SkillPositionCalculationMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MousePos => "MousePos",
            Self::LookAt => "LookAt",
            Self::SelectedTarget => "SelectedTarget",
            Self::CasterPosition => "CasterPosition",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MousePos" => Some(Self::MousePos),
            "LookAt" => Some(Self::LookAt),
            "SelectedTarget" => Some(Self::SelectedTarget),
            "CasterPosition" => Some(Self::CasterPosition),
            _ => None,
        }
    }
}
/// How many times can it hit the same enemy
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SkillTickIntervalMode {
    MultipleTimes = 0,
    OnlyOnce = 1,
}
impl SkillTickIntervalMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MultipleTimes => "MultipleTimes",
            Self::OnlyOnce => "OnlyOnce",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MultipleTimes" => Some(Self::MultipleTimes),
            "OnlyOnce" => Some(Self::OnlyOnce),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SkillTargetMode {
    /// Can affect to multiple targets
    MultipleTargets = 0,
    /// Once it affects a target it can only affecting the same target
    SingleTarget = 1,
    /// Target yourself, useful for heals
    Self_ = 2,
}
impl SkillTargetMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MultipleTargets => "MultipleTargets",
            Self::SingleTarget => "SingleTarget",
            Self::Self_ => "Self",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MultipleTargets" => Some(Self::MultipleTargets),
            "SingleTarget" => Some(Self::SingleTarget),
            "Self" => Some(Self::Self_),
            _ => None,
        }
    }
}
/// When doing a skill with area effect who should it affects?
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SkillAoETargetType {
    /// Default option, skills affect enemies
    Enemies = 0,
    /// E.G. when using a mass heal
    Allies = 1,
}
impl SkillAoETargetType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Enemies => "Enemies",
            Self::Allies => "Allies",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Enemies" => Some(Self::Enemies),
            "Allies" => Some(Self::Allies),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StatusType {
    /// the effect modifies the stats of the target, more HP/stats/crit/regen, or less (curses)
    StatModifier = 0,
}
impl StatusType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StatModifier => "StatModifier",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "StatModifier" => Some(Self::StatModifier),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StatType {
    DamageStat = 0,
    CriticalRate = 1,
    /// MaxHp = 3; TODO
    CriticalDamage = 2,
}
impl StatType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DamageStat => "DamageStat",
            Self::CriticalRate => "CriticalRate",
            Self::CriticalDamage => "CriticalDamage",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DamageStat" => Some(Self::DamageStat),
            "CriticalRate" => Some(Self::CriticalRate),
            "CriticalDamage" => Some(Self::CriticalDamage),
            _ => None,
        }
    }
}
/// Quests abuse the inventory items
/// A quest exists in the inventory as an id and its value is its state
/// Quest value 0 means is not available for the player
/// 1 = Available, means quest can be started
/// 2 = InProgress, means quest is started and when finished can be collected
/// 3 = Collected, means the quest has been collected and now is done
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QuestDefinitionComponent {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantAvailableItemsComponent {
    #[prost(message, repeated, tag="1")]
    pub available_transactions: ::prost::alloc::vec::Vec<protobuf_itemdefinition::ItemDefinitionRef>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapComponent {
    #[prost(message, repeated, tag="1")]
    pub teleporter: ::prost::alloc::vec::Vec<Teleporter>,
    /// Collision data
    #[prost(message, optional, tag="2")]
    pub map_data: ::core::option::Option<MeshData>,
    #[prost(message, repeated, tag="3")]
    pub spawn_points: ::prost::alloc::vec::Vec<SpawnPoint>,
    #[prost(uint32, tag="4")]
    pub max_enemies: u32,
    /// Used on the client side to map which scene to load
    #[prost(int32, tag="5")]
    pub map_index: i32,
}
/// When present, the given map is allowed to perform combat actions (use skill), but not the following:
/// equip/unequip, start/claim quest, use ability points
/// Otherwise, the opposite set of actions is allowed
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MapIsCombatEnabledComponent {
}
/// Must only be present on one map, this one will be the first map for every new player
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MapIsInitialMapComponent {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MobComponent {
    #[prost(uint64, tag="1")]
    pub max_hp: u64,
    #[prost(uint32, tag="2")]
    pub movement_speed: u32,
    #[prost(uint64, tag="3")]
    pub xp: u64,
    #[prost(message, optional, tag="4")]
    pub loot_table: ::core::option::Option<LootTable>,
}
/// Defines the attributes that item inventories may roll (this is the definition)
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryAttributeRollDefinition {
    #[prost(uint64, tag="1")]
    pub min_value: u64,
    #[prost(uint64, tag="2")]
    pub max_value: u64,
    /// 1 by default, use to produce fixed scaled values (e.g. 5, 10, 15)
    #[prost(float, tag="3")]
    pub result_multiplier: f32,
    /// Used to make some attributes more rare than others
    #[prost(uint32, tag="4")]
    pub weight: u32,
    #[prost(enumeration="ItemAttributeDefinition", tag="5")]
    pub item_attribute_definition: i32,
}
/// When IsEquipped, it indicates which slot does it take
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OccupiesEquipmentSlotComponent {
    #[prost(enumeration="EquipmentSlot", tag="1")]
    pub value: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GivesPhysicalDefenceComponent {
    #[prost(int64, tag="1")]
    pub value: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GivesMagicalDefenceComponent {
    #[prost(int64, tag="1")]
    pub value: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GivesPhysicalDamageComponent {
    #[prost(int64, tag="1")]
    pub value: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GivesMagicalDamageComponent {
    #[prost(int64, tag="1")]
    pub value: i64,
}
/// There may be mechanisms to evolve an item (called +1, +2, +3) by paying certain costs and using a specific device/feature
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CanEvolveIntoItemComponent {
    #[prost(uint64, tag="1")]
    pub inventory_item_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CanRollAttributesComponent {
    #[prost(uint32, tag="1")]
    pub min_attribute_count: u32,
    #[prost(uint32, tag="2")]
    pub max_attribute_count: u32,
    #[prost(uint64, repeated, tag="3")]
    pub attribute_definition_id: ::prost::alloc::vec::Vec<u64>,
}
// / COMPONENTS

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterDefinitionComponent {
    #[prost(int32, tag="1")]
    pub base_hp: i32,
    #[prost(int32, tag="2")]
    pub base_strength: i32,
    #[prost(int32, tag="3")]
    pub base_agility: i32,
    #[prost(int32, tag="4")]
    pub base_intelligence: i32,
    #[prost(int32, tag="5")]
    pub base_movement_speed: i32,
    #[prost(message, repeated, tag="6")]
    pub initial_inventory: ::prost::alloc::vec::Vec<protobuf_itemdefinition::ItemDefinitionRefAmount>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsCharacterXpComponent {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsCharacterLevelComponent {
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsCurrentCharacterSlotCountComponent {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LevelRequiredExperienceComponent {
    #[prost(uint64, repeated, tag="1")]
    pub required_exp_for_level: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AbilityPointsPerLevelSingletonComponent {
    #[prost(uint32, tag="1")]
    pub points_per_level: u32,
}
/// The maximum capacity a character (or player) can have in their inventory. Notice this only affects items which do not have the component InventoryHiddenItemComponent
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MaximumVisibleInventoryCapacitySingletonComponent {
    #[prost(uint32, tag="1")]
    pub capacity: u32,
}
/// The amount of extra gold it would cost to buy from NPCs for inventory items. A value of 1.5 means you'd have to pay a 150% of the selling value.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryItemBaseBuyFromNpcValueSingletonComponent {
    #[prost(float, tag="1")]
    pub percentage_value: f32,
}
/// Values for initializing a new character
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryInitialValueCharacterComponent {
    #[prost(int64, tag="1")]
    pub value: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BehaviourTreeComponent {
    #[prost(message, optional, tag="1")]
    pub start_node: ::core::option::Option<BtNode>,
}
// @@protoc_insertion_point(module)
