// @generated
// This file is @generated by prost-build.
/// Register a new user with a unique ID
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag="1")]
    pub player_uuid: ::prost::alloc::string::String,
}
/// Server responds with a token if registration succeeds
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(string, tag="1")]
    pub player_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Ok = 0,
    UnknownError = 1,
    NotImplemented = 2,
    InvalidRequest = 3,
    Timeout = 4,
    NotFound = 5,
    PermissionDenied = 6,
    UserAlreadyExists = 7,
    InvalidToken = 8,
    AuthenticationFailed = 9,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ok => "OK",
            Self::UnknownError => "UNKNOWN_ERROR",
            Self::NotImplemented => "NOT_IMPLEMENTED",
            Self::InvalidRequest => "INVALID_REQUEST",
            Self::Timeout => "TIMEOUT",
            Self::NotFound => "NOT_FOUND",
            Self::PermissionDenied => "PERMISSION_DENIED",
            Self::UserAlreadyExists => "USER_ALREADY_EXISTS",
            Self::InvalidToken => "INVALID_TOKEN",
            Self::AuthenticationFailed => "AUTHENTICATION_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OK" => Some(Self::Ok),
            "UNKNOWN_ERROR" => Some(Self::UnknownError),
            "NOT_IMPLEMENTED" => Some(Self::NotImplemented),
            "INVALID_REQUEST" => Some(Self::InvalidRequest),
            "TIMEOUT" => Some(Self::Timeout),
            "NOT_FOUND" => Some(Self::NotFound),
            "PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "USER_ALREADY_EXISTS" => Some(Self::UserAlreadyExists),
            "INVALID_TOKEN" => Some(Self::InvalidToken),
            "AUTHENTICATION_FAILED" => Some(Self::AuthenticationFailed),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoRequest {
    #[prost(uint64, tag="1")]
    pub message_id: u64,
    #[prost(message, optional, tag="2")]
    pub any_payload: ::core::option::Option<::prost_types::Any>,
    #[prost(uint64, tag="3")]
    pub message_timestamp: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoResponse {
    #[prost(uint64, tag="1")]
    pub message_id: u64,
    #[prost(message, optional, tag="2")]
    pub any_payload: ::core::option::Option<::prost_types::Any>,
    #[prost(uint64, tag="3")]
    pub server_now: u64,
    #[prost(enumeration="ErrorCode", tag="4")]
    pub error: i32,
}
/// Login using ID and token
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag="1")]
    pub player_uuid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
}
/// Server confirms success
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag="1")]
    pub player_uuid: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
