use crate::ItemDefinition;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

pub fn generate_item_definition_service(definitions: &[ItemDefinition], proto_path: Vec<&str>) {
    let out_dir = env::var("OUT_DIR").unwrap();

    // Discover all unique component types
    let component_types = discover_component_types(proto_path, definitions);

    let item_definition_service_impl_code = generate_item_definition_service_impl(&component_types);
    let item_definition_service_impl_path = Path::new(&out_dir).join("item_definition_lookup_service_impl.rs");
    fs::write(&item_definition_service_impl_path, item_definition_service_impl_code).expect("Failed to write item_definition_lookup_service_impl.rs");

    let component_lookups_path = Path::new(&out_dir).join("component_lookups.rs");
    let generated_code = generate_component_lookups(&component_types, definitions);
    fs::write(&component_lookups_path, generated_code).expect("Failed to write component_lookups.rs");
}

fn get_all_proto_ending_with(proto_path: &str, ends_with: &str) -> HashSet<String> {
    let content = fs::read_to_string(proto_path).expect(&format!("Failed to read {}", proto_path));

    let mut requests = HashSet::new();
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with("pub struct ") {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 3 {
                let name_part = parts[2];
                // Clean up in case the opening brace is attached or there are other characters
                let struct_name = name_part.trim_end_matches('{').trim();

                if struct_name.ends_with(ends_with) {
                    requests.insert(struct_name.to_string());
                }
            }
        }
    }
    requests
}

fn generate_item_definition_service_impl(component_types: &HashSet<String>) -> String {
    let mut singleton_component_types = vec![];
    let mut component_lookup_types = vec![];
    component_types.iter().for_each(|component_type| {
        let component_type_clean = component_type.split("::").last().unwrap();
        if is_singleton_component(component_type) {
            singleton_component_types.push(component_type_clean)
        } else {
            component_lookup_types.push(component_type_clean)
        }
    });

    let mut code = String::new();
    code.push_str(&format!(
r#"
// This code is autogenerated by build.rs
// Processing this component_types:
// {:?}

pub trait ItemDefinitionLookupService {{
{}
}}

#[derive(Default, Debug)]
pub struct ItemDefinitionLookupServiceImpl {{}}

impl ItemDefinitionLookupService for ItemDefinitionLookupServiceImpl {{

"#, component_types, generate_trait(&singleton_component_types, &component_lookup_types)));

    for component_type in component_types {
        let component_type_clean = component_type.split("::").last().unwrap();
        if is_singleton_component(component_type) {
            let fn_definition = component_name_to_singleton_fn_impl(component_type_clean);
            code.push_str(fn_definition.as_str());
        } else {
            let fn_definition = component_name_to_fn_impl(component_type_clean);
            code.push_str(fn_definition.as_str());
            let fn_definition_all = component_name_to_fn_impl_all(component_type_clean);
            code.push_str(fn_definition_all.as_str());
        }
    }
    code.push_str("}\n");

    code.push_str(&generate_item_definition_lookup_dynamic_impl(&singleton_component_types, &component_lookup_types));

    code
}

fn generate_item_definition_lookup_dynamic_impl(
    singleton_component_types: &Vec<&str>,
    component_lookup_types: &Vec<&str>,
) -> String {
    let mut code = String::new();
    let members_impl = generate_lookup_dynamic_members(&singleton_component_types, &component_lookup_types);
    let singleton_deconstructions = generate_lookup_dynamic_singleton_deconstructions(&singleton_component_types);
    let constructor_fill = generate_lookup_dynamic_constructor_fill(&singleton_component_types, &component_lookup_types);
    let singletons_fn_impl = generate_lookup_dynamic_singletons_fn_impl(&singleton_component_types);
    let lookup_fn_impl = generate_lookup_dynamic_lookup_fn_impl(&component_lookup_types);
    code.push_str(&format!(
        r#"
pub struct ItemDefinitionLookupDynamicImpl {{
{members_impl}
}}

impl ItemDefinitionLookupDynamicImpl {{
    pub fn new(
        item_definitions: &ItemDefinitionsResponse,
    ) -> Result<Self, ItemDefinitionLookupDynamicError> {{
        let mut indexes_by_component_type_url: HashMap<String, Vec<(u64, &prost_types::Any)>> = Default::default();
        item_definitions.definitions.iter().for_each(|item| {{
            item.any_components.iter().for_each(|component| {{
                let type_url = component.type_url.clone();
                match indexes_by_component_type_url
                    .get_mut(&type_url) {{
                    None => {{
                        indexes_by_component_type_url.insert(type_url, vec![(item.id, component)]);
                    }},
                    Some(vec) => vec.push((item.id, component)),
                }}
            }})}});

        {singleton_deconstructions}

        Ok(Self{{
        {constructor_fill}
        }})
    }}
}}

impl ItemDefinitionLookupService for ItemDefinitionLookupDynamicImpl {{
{singletons_fn_impl}
{lookup_fn_impl}
}}
"#));
    code
}

fn generate_lookup_dynamic_singletons_fn_impl(
    singleton_component_types: &Vec<&str>,
) -> String {
    let mut code = String::new();
    singleton_component_types.iter().for_each(|component_type_name| {
        let member_name = as_member_name(component_type_name);
        code.push_str(&format!(
            r#"
        fn {member_name}(&self) -> std::sync::Arc<{component_type_name}> {{ self.{member_name}.clone() }}
        fn {member_name}_id(&self) -> u64 {{ self.{member_name}_id }}"#));
    });
    code
}

fn generate_lookup_dynamic_lookup_fn_impl(
    component_lookup_types: &Vec<&str>,
) -> String {
    let mut code = String::new();
    component_lookup_types.iter().for_each(|component_type_name| {
        let member_name = as_member_name(component_type_name);
        code.push_str(&format!(
r#"
        fn {member_name}_component(&self, id: &u64) ->Option<std::sync::Arc<{component_type_name}>>{{ self.{member_name}.get(id).cloned() }}
        fn {member_name}_component_all(&self) -> Vec<(&u64, std::sync::Arc<{component_type_name}>)> {{ self.{member_name}.iter().map(|(k, v)| (k, std::sync::Arc::clone(v))).collect() }}"#
        ));
    });
    code
}

fn generate_lookup_dynamic_singleton_deconstructions(
    singleton_component_types: &Vec<&str>,
) -> String {
    let mut code = String::new();
    singleton_component_types.iter().for_each(|component_type_name| {
        let member_name = as_member_name(component_type_name);
        code.push_str(&format!(
r#"
        let ({member_name}_id, {member_name}) = get_singleton_component::<{component_type_name}>(&indexes_by_component_type_url)?;"#));
    });
    code
}

fn generate_lookup_dynamic_constructor_fill(
    singleton_component_types: &Vec<&str>,
    component_lookup_types: &Vec<&str>,
) -> String {
    let mut code = String::new();
    singleton_component_types.iter().for_each(|component_type_name| {
        let member_name = as_member_name(component_type_name);
        code.push_str(&format!(
r#"
            {member_name},
            {member_name}_id,"#));
    });
    component_lookup_types.iter().for_each(|component_type_name| {
        let member_name = as_member_name(component_type_name);
        code.push_str(&format!(
r#"
            {member_name}: get_hash_map::<{component_type_name}>(&indexes_by_component_type_url),"#
        ));
    });
    code
}

fn generate_lookup_dynamic_members(
    singleton_component_types: &Vec<&str>,
    component_lookup_types: &Vec<&str>,
) -> String {
    let mut code = String::new();
    singleton_component_types.iter().for_each(|component_type_name| {
        let member_name = as_member_name(component_type_name);
        code.push_str(&format!(
r#"
    {member_name}: std::sync::Arc<{component_type_name}>,
    {member_name}_id: u64,"#));
    });
    component_lookup_types.iter().for_each(|component_type_name|{
        let member_name = as_member_name(component_type_name);
       code.push_str(&format!(
r#"
    {member_name}: std::collections::HashMap<u64, std::sync::Arc<{component_type_name}>>,"#));
    });

    code
}

fn as_member_name(
    component_type_name: &str,
) -> String {
    let component_name_no_component = component_type_name.replace("Component", "").to_string();
    let member_name = to_snake_case_lower(component_name_no_component.as_str());
    member_name
}

fn generate_trait(
    singleton_component_types: &Vec<&str>,
    component_type_lookups: &Vec<&str>
) -> String {
    let mut code = String::new();
    for singleton in singleton_component_types.iter(){
        let fn_definition = component_name_to_singleton_fn_trait(singleton);
        code.push_str(fn_definition.as_str());
    }
    for component_type in component_type_lookups.iter() {
        let component_type_clean = component_type.split("::").last().unwrap();
        let fn_definition = component_name_to_fn_trait(component_type_clean);
        code.push_str(fn_definition.as_str());
        let fn_definition_all = component_name_to_fn_trait_all(component_type_clean);
        code.push_str(fn_definition_all.as_str());
    }
    code
}

fn generate_component_lookups(component_types: &HashSet<String>, definitions: &[ItemDefinition]) -> String {
    let mut code = String::new();
    code.push_str("use std::collections::HashMap;\n");
    code.push_str("use proto_gen::*;\n");
    code.push_str("use ::protobuf_itemdefinition::*;\n");
    code.push_str("use prost::Message;\n\n");
    code.push_str("use std::sync::{Arc, LazyLock};\n\n");
    code.push_str("const ITEM_DEFS_BYTES: &[u8] = include_bytes!(\"../../../../../data/ItemDefinitions.bytes\");\n\n");

    code.push_str(
        "static ITEM_DEFINITIONS_RESPONSE_DEFAULT: LazyLock<ItemDefinitionsResponse> =\
     LazyLock::new(|| ItemDefinitionsResponse::decode(ITEM_DEFS_BYTES).unwrap_or_default());\n\n",
    );

    // Generate hashmaps for each component type
    for component_type in component_types {
        let static_name = component_type_to_static_name(component_type);
        code.push_str(&generate_component_lookup(
            component_type,
            static_name,
            definitions,
        ));
    }
    code
}

fn discover_component_types(
    proto_paths: Vec<&str>,
    definitions: &[ItemDefinition],
) -> HashSet<String> {
    let mut component_types = HashSet::new();

    for def in definitions {
        for component in &def.any_components {
            // Extract the component type name from the type_url
            if let Some(type_name) = extract_component_type_name(&component.type_url) {
                component_types.insert(type_name);
            }
        }
    }
    for proto_path in proto_paths {
        let namespace = proto_path.split('/').next_back().unwrap().replace(".rs", "");
        let proto_components = get_all_proto_ending_with(proto_path, "Component");
        for proto_component in proto_components {
            if !component_types.contains(&proto_component) {
                component_types.insert(format!("{}::{}", namespace, proto_component));
            }
        }
    }

    component_types
}

fn extract_component_type_name(type_url: &str) -> Option<String> {
    // Extract the last part of the type URL (e.g., "CharacterDefinitionComponent" from "type.googleapis.com/CharacterDefinitionComponent")
    type_url.split('/').next_back().map(|s| s.replace('.', "::"))
}

fn component_name_to_singleton_fn_impl(component_type_name: &str) -> String {
    let component_name_no_component = component_type_name.replace("Component", "").to_string();
    let lookup_name = to_snake_case_upper(component_name_no_component.as_str());
    let function_name = to_snake_case_lower(component_name_no_component.as_str());
    let mut code = String::new();
    code.push_str(&format!(
        r#"
    fn {}(&self) -> std::sync::Arc<{}> {{
        {}.clone()
    }}

    fn {}_id(&self) -> u64 {{
        {}_ID
    }}
"#,
        function_name, component_type_name,
        lookup_name,
        function_name, lookup_name,
    ));
    code
}

fn component_name_to_singleton_fn_trait(component_type_name: &str) -> String {
    let component_name_no_component = component_type_name.replace("Component", "").to_string();
    let function_name = to_snake_case_lower(component_name_no_component.as_str());
    let mut code = String::new();
    code.push_str(&format!(
        r#"
    fn {}(&self) -> std::sync::Arc<{}>;

    fn {}_id(&self) -> u64;
"#,
        function_name, component_type_name,
        function_name,
    ));
    code
}

fn component_name_to_fn_impl(component_name: &str) -> String {
    let lookup_name = to_snake_case_upper(&format!("{}Lookup",component_name));
    let mut code = String::new();
    code.push_str(&format!("    fn {}(&self, id: &u64) -> Option<std::sync::Arc<{}>>", to_snake_case_lower(component_name), component_name));
    code.push_str("{\n");
    code.push_str(&format!("        {}.get(id).cloned()\n", lookup_name));
    code.push_str("    }\n");
    code
}

fn component_name_to_fn_trait(component_name: &str) -> String {
    let mut code = String::new();
    code.push_str(&format!("    fn {}(&self, id: &u64) -> Option<std::sync::Arc<{}>>;\n", to_snake_case_lower(component_name), component_name));
    code
}

fn component_name_to_fn_impl_all(component_name: &str) -> String {
    let lookup_name = to_snake_case_upper(&format!("{}Lookup",component_name));
    let mut code = String::new();
    code.push_str(&format!("    fn {}_all(&self) -> Vec<(&u64, std::sync::Arc<{}>)>", to_snake_case_lower(component_name), component_name));
    code.push_str(" {\n");
    code.push_str(&format!("        {}.iter().map(|(k, v)| (k, Arc::clone(v))).collect()\n", lookup_name));
    code.push_str("    }\n");
    code
}

fn component_name_to_fn_trait_all(component_name: &str) -> String {
    let mut code = String::new();
    code.push_str(&format!("    fn {}_all(&self) -> Vec<(&u64, std::sync::Arc<{}>)>;\n", to_snake_case_lower(component_name), component_name));
    code
}

fn generate_component_lookup(
    component_type: &str,
    static_name: String,
    definitions: &[ItemDefinition],
) -> String {
    let mut code = String::new();
    let component_type_clean = component_type.split("::").last().unwrap().to_string();
    // Add components to the map
    let indexes: Vec<(usize, usize, u64)> = definitions.iter().enumerate().flat_map(|(definition_index, def)| {
        def.any_components.iter().enumerate().filter_map(move |(component_index, component)| {
            let component_type_url = format!("type.googleapis.com/{}", component_type.replace("::", "."));
            if component.type_url.contains(component_type_url.as_str()) {
                Some((definition_index, component_index, def.id))
            } else {
                None
            }
        })
    }).collect::<Vec<_>>();

    if is_singleton_component(&static_name) {
        let singleton_variable_name = to_snake_case_upper(static_name.replace("ComponentLookup", "").as_str());
        let singleton_id = indexes.iter().map(|(_, _, id)| *id).min().unwrap_or_default();
        let singleton_impl = indexes.iter().map(|(definition_index, component_index, _)| {
            format!(
                r#"
    let component = &ITEM_DEFINITIONS_RESPONSE_DEFAULT.definitions[{}].any_components[{}];
    let decoded_component = {}::decode(component.value.as_slice()).unwrap();
    Arc::new(decoded_component)
"#,
                definition_index,
                component_index,
                component_type_clean,
            )}).collect::<Vec<_>>();
        code.push_str(&format!(
            r#"
#[allow(dead_code)]
pub static {}: LazyLock<Arc<{}>> = LazyLock::new(|| {{
{}
}});

#[allow(dead_code)]
pub const {}_ID: u64 = {};
"#,
            singleton_variable_name,
            component_type_clean,
            singleton_impl.join("\n"),
            singleton_variable_name,
            singleton_id,
        ));
        return code;
    }
    code.push_str(&format!(
        "#[allow(dead_code)]\npub static {}: LazyLock<HashMap<u64, Arc<{}>>> = LazyLock::new(|| {{\n",
        to_snake_case_upper(static_name.as_str()), component_type_clean
    ));
    let mutability = match indexes.is_empty() {
        true => "",
        false => "mut",
    };
    code.push_str(&format!("    let {mutability} map = HashMap::new();\n"));
    for (definition_index, component_index, definition_id) in indexes.iter() {
        code.push_str(&format!(
            r#"
     {{
        let component = &ITEM_DEFINITIONS_RESPONSE_DEFAULT.definitions[{}].any_components[{}];
        if let Ok(decoded_component) = {}::decode(component.value.as_slice()) {{
            map.insert({}, Arc::new(decoded_component));
        }}
     }}
"#,
            definition_index, component_index,
            component_type_clean,
            definition_id,
        ));
    }
    code.push_str("    map\n");
    code.push_str("});\n\n");
    code
}

fn is_singleton_component(static_name: &String) -> bool {
    if static_name.to_lowercase().contains("singleton") {
        return true;
    }
    false
}

fn component_type_to_static_name(component_type: &str) -> String {
    let result = component_type.split("::").last().unwrap().to_string();
    format!("{}Lookup", result)
}

fn to_snake_case_upper(s: &str) -> String {
    let mut chars = s.chars();
    let mut snake = String::new();
    if let Some(first) = chars.next() {
        snake.push(first.to_uppercase().next().unwrap());
    }
    for c in chars {
        if c.is_uppercase() {
            snake.push('_');
            snake.push(c.to_uppercase().next().unwrap());
        } else{
            snake.push(c.to_uppercase().next().unwrap());
        }
    }
    snake
}

fn to_snake_case_lower(s: &str) -> String {
    let mut chars = s.chars();
    let mut snake = String::new();
    if let Some(first) = chars.next() {
        snake.push(first.to_lowercase().next().unwrap());
    }
    for c in chars {
        if c.is_uppercase() {
            snake.push('_');
            snake.push(c.to_lowercase().next().unwrap());
        } else{
            snake.push(c.to_lowercase().next().unwrap());
        }
    }
    snake
}

