use crate::ItemDefinition;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

pub fn generate_item_definition_service(definitions: &[ItemDefinition], proto_path: &str) {
    let out_dir = env::var("OUT_DIR").unwrap();

    // Discover all unique component types
    let component_types = discover_component_types(proto_path, definitions);

    let item_definition_service_impl_code = generate_item_definition_service_impl(&component_types);
    let item_definition_service_impl_path = Path::new(&out_dir).join("item_definition_lookup_service_impl.rs");
    fs::write(&item_definition_service_impl_path, item_definition_service_impl_code).expect("Failed to write item_definition_lookup_service_impl.rs");

    let component_lookups_path = Path::new(&out_dir).join("component_lookups.rs");
    let generated_code = generate_component_lookups(&component_types, definitions);
    fs::write(&component_lookups_path, generated_code).expect("Failed to write component_lookups.rs");
}

fn get_all_proto_ending_with(proto_path: &str, ends_with: &str) -> HashSet<String> {
    let content = fs::read_to_string(proto_path).expect(&format!("Failed to read {}", proto_path));

    let mut requests = HashSet::new();
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with("pub struct ") {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 3 {
                let name_part = parts[2];
                // Clean up in case the opening brace is attached or there are other characters
                let struct_name = name_part.trim_end_matches('{').trim();

                if struct_name.ends_with(ends_with) {
                    requests.insert(struct_name.to_string());
                }
            }
        }
    }
    requests
}

fn generate_item_definition_service_impl(component_types: &HashSet<String>) -> String {
    let mut code = String::new();
    code.push_str(&format!(
r#"
// This code is autogenerated by build.rs
// Processing this component_types:
// {:?}

#[derive(Default, Debug)]
pub struct ItemDefinitionLookupServiceImpl {{}}
impl ItemDefinitionLookupServiceImpl {{

"#, component_types));
    for component_type in component_types {
        let component_type_clean = component_type.split("::").last().unwrap();
        if is_singleton_component(component_type) {
            let fn_definition = component_name_to_singleton_fn_impl(component_type_clean);
            code.push_str(fn_definition.as_str());
        } else {
            let fn_definition = component_name_to_fn_impl(component_type_clean);
            code.push_str(fn_definition.as_str());
            let fn_definition_all = component_name_to_fn_impl_all(component_type_clean);
            code.push_str(fn_definition_all.as_str());
        }
    }
    code.push_str("}\n");
    code
}

fn generate_component_lookups(component_types: &HashSet<String>, definitions: &[ItemDefinition]) -> String {
    let mut code = String::new();
    code.push_str("use std::collections::HashMap;\n");
    code.push_str("use once_cell::sync::Lazy;\n");
    code.push_str("use proto_gen::*;\n");
    code.push_str("use ::protobuf_itemdefinition::*;\n");
    code.push_str("use prost::Message;\n\n");
    code.push_str("use std::sync::Arc;\n\n");
    code.push_str("const ITEM_DEFS_BYTES: &[u8] = include_bytes!(\"../../../../../data/ItemDefinitions.bytes\");\n\n");

    code.push_str(
        "static ITEM_DEFINITIONS_RESPONSE_DEFAULT: Lazy<ItemDefinitionsResponse> =\
     Lazy::new(|| ItemDefinitionsResponse::decode(ITEM_DEFS_BYTES).unwrap_or_default());\n\n",
    );

    // Generate hashmaps for each component type
    for component_type in component_types {
        let static_name = component_type_to_static_name(component_type);
        code.push_str(&generate_component_lookup(
            component_type,
            static_name,
            definitions,
        ));
    }
    code
}

fn discover_component_types(
    proto_path: &str,
    definitions: &[ItemDefinition],
) -> HashSet<String> {
    let mut component_types = HashSet::new();

    for def in definitions {
        for component in &def.any_components {
            // Extract the component type name from the type_url
            if let Some(type_name) = extract_component_type_name(&component.type_url) {
                component_types.insert(type_name);
            }
        }
    }

    let proto_components = get_all_proto_ending_with(proto_path,"Component");
    for proto_component in proto_components {
        if !component_types.contains(&proto_component) {
            component_types.insert(format!("proto_balancing::{}",proto_component));
        }
    }

    component_types
}

fn extract_component_type_name(type_url: &str) -> Option<String> {
    // Extract the last part of the type URL (e.g., "CharacterDefinitionComponent" from "type.googleapis.com/CharacterDefinitionComponent")
    type_url.split('/').next_back().map(|s| s.replace('.', "::"))
}

fn component_name_to_singleton_fn_impl(component_type_name: &str) -> String {
    let component_name_no_component = component_type_name.replace("Component", "").to_string();
    let lookup_name = to_snake_case_upper(component_name_no_component.as_str());
    let function_name = to_snake_case_lower(component_name_no_component.as_str());
    let mut code = String::new();
    code.push_str(&format!(
        r#"
    pub fn {}(&self) -> std::sync::Arc<{}> {{
        {}.clone()
    }}

    pub fn {}_id(&self) -> u64 {{
        {}_ID
    }}
"#,
        function_name, component_type_name,
        lookup_name,
        function_name, lookup_name,
    ));
    code
}

fn component_name_to_fn_impl(component_name: &str) -> String {
    let lookup_name = to_snake_case_upper(&format!("{}Lookup",component_name));
    let mut code = String::new();
    code.push_str(&format!("    pub fn {}(&self, id: &u64) -> Option<std::sync::Arc<{}>>", to_snake_case_lower(component_name), component_name));
    code.push_str("{\n");
    code.push_str(&format!("        {}.get(id).cloned()\n", lookup_name));
    code.push_str("    }\n");
    code
}

fn component_name_to_fn_impl_all(component_name: &str) -> String {
    let lookup_name = to_snake_case_upper(&format!("{}Lookup",component_name));
    let mut code = String::new();
    code.push_str(&format!("    pub fn {}_all(&self) -> Vec<(&u64, std::sync::Arc<{}>)>", to_snake_case_lower(component_name), component_name));
    code.push_str(" {\n");
    code.push_str(&format!("        {}.iter().map(|(k, v)| (k, Arc::clone(v))).collect()\n", lookup_name));
    code.push_str("    }\n");
    code
}

fn generate_component_lookup(
    component_type: &str,
    static_name: String,
    definitions: &[ItemDefinition],
) -> String {
    let mut code = String::new();
    let component_type_clean = component_type.split("::").last().unwrap().to_string();
    // Add components to the map
    let indexes: Vec<(usize, usize, u64)> = definitions.iter().enumerate().flat_map(|(definition_index, def)| {
        def.any_components.iter().enumerate().filter_map(move |(component_index, component)| {
            let component_type_url = format!("type.googleapis.com/{}", component_type.replace("::", "."));
            if component.type_url.contains(component_type_url.as_str()) {
                Some((definition_index, component_index, def.id))
            } else {
                None
            }
        })
    }).collect::<Vec<_>>();

    if is_singleton_component(&static_name) {
        let singleton_variable_name = to_snake_case_upper(static_name.replace("ComponentLookup", "").as_str());
        let singleton_id = indexes.iter().map(|(_, _, id)| *id).min().unwrap_or_default();
        let singleton_impl = indexes.iter().map(|(definition_index, component_index, definition_id)| {
            format!(
                r#"
    let component = &ITEM_DEFINITIONS_RESPONSE_DEFAULT.definitions[{}].any_components[{}];
    let decoded_component = {}::decode(component.value.as_slice()).unwrap();
    Arc::new(decoded_component)
"#,
                definition_index,
                component_index,
                component_type_clean,
            )}).collect::<Vec<_>>();
        code.push_str(&format!(
            r#"
pub static {}: Lazy<Arc<{}>> = Lazy::new(|| {{
{}
}});

pub const {}_ID: u64 = {};
"#,
            singleton_variable_name,
            component_type_clean,
            singleton_impl.join("\n"),
            singleton_variable_name,
            singleton_id,
        ));
        return code;
    }
    code.push_str(&format!(
        "pub static {}: Lazy<HashMap<u64, Arc<{}>>> = Lazy::new(|| {{\n",
        to_snake_case_upper(static_name.as_str()), component_type_clean
    ));
    code.push_str("    let mut map = HashMap::new();\n");
    for (definition_index, component_index, definition_id) in indexes.iter() {
        code.push_str(&format!(
            r#"
     {{
        let component = &ITEM_DEFINITIONS_RESPONSE_DEFAULT.definitions[{}].any_components[{}];
        if let Ok(decoded_component) = {}::decode(component.value.as_slice()) {{
            map.insert({}, Arc::new(decoded_component));
        }}
     }}
"#,
            definition_index, component_index,
            component_type_clean,
            definition_id,
        ));
    }
    code.push_str("    map\n");
    code.push_str("});\n\n");
    code
}

fn is_singleton_component(static_name: &String) -> bool {
    if static_name.to_lowercase().contains("singleton") {
        return true;
    }
    false
}

fn component_type_to_static_name(component_type: &str) -> String {
    let result = component_type.split("::").last().unwrap().to_string();
    format!("{}Lookup", result)
}

fn to_snake_case_upper(s: &str) -> String {
    let mut chars = s.chars();
    let mut snake = String::new();
    if let Some(first) = chars.next() {
        snake.push(first.to_uppercase().next().unwrap());
    }
    for c in chars {
        if c.is_uppercase() {
            snake.push('_');
            snake.push(c.to_uppercase().next().unwrap());
        } else{
            snake.push(c.to_uppercase().next().unwrap());
        }
    }
    snake
}

fn to_snake_case_lower(s: &str) -> String {
    let mut chars = s.chars();
    let mut snake = String::new();
    if let Some(first) = chars.next() {
        snake.push(first.to_lowercase().next().unwrap());
    }
    for c in chars {
        if c.is_uppercase() {
            snake.push('_');
            snake.push(c.to_lowercase().next().unwrap());
        } else{
            snake.push(c.to_lowercase().next().unwrap());
        }
    }
    snake
}

