// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemDefinition {
    /// unique asset id
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(message, repeated, tag="2")]
    pub any_components: ::prost::alloc::vec::Vec<::prost_types::Any>,
}
/// This way we can create custom editors for this and author data easier
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ItemDefinitionRef {
    #[prost(uint64, tag="1")]
    pub id: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ItemDefinitionRefAmount {
    #[prost(message, optional, tag="1")]
    pub item_ref: ::core::option::Option<ItemDefinitionRef>,
    #[prost(uint64, tag="2")]
    pub amount: u64,
}
/// Represents an item and its quantity
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionItem {
    #[prost(message, optional, tag="1")]
    pub id_ref: ::core::option::Option<ItemDefinitionRef>,
    #[prost(uint64, tag="2")]
    pub value: u64,
    /// Used in dynamic transactions on server side to define an exact item to be consumed instead of a type
    #[prost(string, tag="3")]
    pub item_instance_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionReward {
    #[prost(message, optional, tag="1")]
    pub id_ref: ::core::option::Option<ItemDefinitionRef>,
    #[prost(uint64, tag="2")]
    pub value: u64,
    #[prost(uint64, tag="3")]
    pub value_min: u64,
    #[prost(uint64, tag="4")]
    pub value_max: u64,
    /// Duration in seconds
    #[prost(uint64, tag="5")]
    pub duration: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionWeightedReward {
    #[prost(message, optional, tag="1")]
    pub reward: ::core::option::Option<TransactionReward>,
    #[prost(uint32, tag="2")]
    pub weight: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionInstance {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub endtime: u64,
    #[prost(message, optional, tag="3")]
    pub reward: ::core::option::Option<TransactionItem>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionInstancesRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionInstancesResponse {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<TransactionInstance>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ItemsErrorCode {
    OkItems = 0,
    // ONES ABOVE ARE CORE ERRORS

    NotEnoughItems = 100,
    TransactionInvalid = 101,
    TransactionNotFinished = 102,
    InvalidItemDefinition = 103,
    NotEnoughInventorySpace = 104,
    InvalidItemInstance = 105,
    TransactionRequirementsNotMet = 106,
}
impl ItemsErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OkItems => "OK_ITEMS",
            Self::NotEnoughItems => "NOT_ENOUGH_ITEMS",
            Self::TransactionInvalid => "TRANSACTION_INVALID",
            Self::TransactionNotFinished => "TRANSACTION_NOT_FINISHED",
            Self::InvalidItemDefinition => "INVALID_ITEM_DEFINITION",
            Self::NotEnoughInventorySpace => "NOT_ENOUGH_INVENTORY_SPACE",
            Self::InvalidItemInstance => "INVALID_ITEM_INSTANCE",
            Self::TransactionRequirementsNotMet => "TRANSACTION_REQUIREMENTS_NOT_MET",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OK_ITEMS" => Some(Self::OkItems),
            "NOT_ENOUGH_ITEMS" => Some(Self::NotEnoughItems),
            "TRANSACTION_INVALID" => Some(Self::TransactionInvalid),
            "TRANSACTION_NOT_FINISHED" => Some(Self::TransactionNotFinished),
            "INVALID_ITEM_DEFINITION" => Some(Self::InvalidItemDefinition),
            "NOT_ENOUGH_INVENTORY_SPACE" => Some(Self::NotEnoughInventorySpace),
            "INVALID_ITEM_INSTANCE" => Some(Self::InvalidItemInstance),
            "TRANSACTION_REQUIREMENTS_NOT_MET" => Some(Self::TransactionRequirementsNotMet),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ItemDefinitionsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemDefinitionsResponse {
    #[prost(message, repeated, tag="1")]
    pub definitions: ::prost::alloc::vec::Vec<ItemDefinition>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionComponent {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRequiredItemComponent {
    #[prost(message, optional, tag="1")]
    pub required: ::core::option::Option<TransactionItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRequiredNotHavingItemComponent {
    #[prost(message, optional, tag="1")]
    pub required_not_having: ::core::option::Option<TransactionItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionConsumedItemComponent {
    #[prost(message, optional, tag="1")]
    pub consumed: ::core::option::Option<TransactionItem>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionRewardedItemComponent {
    #[prost(message, optional, tag="1")]
    pub rewarded: ::core::option::Option<TransactionReward>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRequiredItemsComponent {
    #[prost(message, repeated, tag="1")]
    pub required: ::prost::alloc::vec::Vec<TransactionItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRequiredNotHavingItemsComponent {
    #[prost(message, repeated, tag="1")]
    pub required_not_having: ::prost::alloc::vec::Vec<TransactionItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionConsumedItemsComponent {
    #[prost(message, repeated, tag="1")]
    pub consumed: ::prost::alloc::vec::Vec<TransactionItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRewardedItemsComponent {
    #[prost(message, repeated, tag="1")]
    pub rewarded: ::prost::alloc::vec::Vec<TransactionReward>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRewardedItemsRandomComponent {
    /// Chose 1 item from each bag
    #[prost(message, repeated, tag="1")]
    pub reward_pools: ::prost::alloc::vec::Vec<ItemDefinitionRef>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolWeightedItemsComponent {
    #[prost(message, repeated, tag="1")]
    pub weighted_rewards: ::prost::alloc::vec::Vec<TransactionWeightedReward>,
}
/// By default all item definitions are enabled, add this component to disable them
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ItemDefinitionDisabledComponent {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DebugNameComponent {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
}
/// Values for initializing a new player
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryInitialValueComponent {
    #[prost(int64, tag="1")]
    pub value: i64,
}
/// The maximum number of elements allowed of a given item type
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryMaxValueComponent {
    #[prost(int64, tag="1")]
    pub value: i64,
}
/// Items with this component are hidden in the inventory and do not take space in it
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InventoryHiddenItemComponent {
}
/// Special attribute which turns items into countable. No other attribute may be present
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsStackableComponent {
}
/// The amount of a given inventory items that this item or attribute adds upon selling to an NPC.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DefaultSellValueComponent {
    /// The item_id for which it sells must be stackable
    #[prost(message, optional, tag="1")]
    pub item_id: ::core::option::Option<ItemDefinitionRef>,
    #[prost(int64, tag="2")]
    pub value: i64,
}
// @@protoc_insertion_point(module)
